### ISSUE TITLE
error

### ISSUE THREAD

**Issue by axenolcen** [Janniqz/pyth-twitter-bot#3]
i get this error messages

Twitter API returned a 400 (Bad Request), Query parameters are missing.
Traceback (most recent call last):
  File "C:\twitterbot\pyth-twitter-bot.py", line 63, in <module>
    ids = user.search(q=PATTERN, result_type="recent", count=AMOUNT)
  File "C:\Users\axeno\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twython\endpoints.py", line 268, in search
    return self.get('search/tweets', params=params)
  File "C:\Users\axeno\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twython\api.py", line 264, in get
    return self.request(endpoint, params=params, version=version)
  File "C:\Users\axeno\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twython\api.py", line 258, in request
    api_call=url)
  File "C:\Users\axeno\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twython\api.py", line 194, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonError: Twitter API returned a 400 (Bad Request), Query parameters are missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\twitterbot\pyth-twitter-bot.py", line 95, in <module>
    print(get_time() + "General Twitter API Error. Retrying after runthrough. Error Message:" + print(error))
TypeError: must be str, not NoneType

**Comment by Janniqz** [comment]
Hey there!

Just going to assume you're trying to like / retweet Tweets with a specific @ or # here.
Please correct me otherwise.

What did you put for the `PATTERN = "XXX"` Parameter in the config? From what I can see it seems to be empty. If you're trying to do a Specific Search you have to put something in there. I'll change the config file tomorrow so it's a bit clearer.
